# Generated by Django 4.0 on 2021-12-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanismanBilgi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('unvan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JuriBilgi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('unvan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='YazarBilgi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ogretim_turu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AnaTablo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ders_adi', models.TextField()),
                ('proje_adi', models.TextField()),
                ('teslim_donemi', models.TextField()),
                ('ozet', models.TextField()),
                ('anahtar', models.TextField()),
                ('danisman_bilgi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.danismanbilgi')),
                ('juri_bilgi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.juribilgi')),
                ('yazar_bilgi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.yazarbilgi')),
            ],
        ),
    ]
