# Generated by Django 4.0 on 2021-12-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_danismanbilgi_juribilgi_yazarbilgi_anatablo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anatablo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='danismanbilgi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='juribilgi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='yazarbilgi',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='yazarbilgi',
            name='ogretim_turu',
            field=models.TextField(),
        ),
    ]
